version: '3.8'

services:
  db:
    restart: always
    image: postgres:14-alpine
    shm_size: 256mb
    networks:
      - internal_network
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - ./postgres14:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'

  redis:
    restart: always
    image: redis:7-alpine
    networks:
      - internal_network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - ./redis:/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # رجیستری اصلی (پیش‌فرض devneeds) – در صورت نیاز به پشتیبان، مقدار را به docker-mirror.liara.ir تغییر دهید
        BASE_REGISTRY: "docker.devneeds.ir"
        # آینه‌های لیارا برای Debian و npm
        DEBIAN_MIRROR: "linux-mirror.liara.ir/repository/debian"
        RUBYGEMS_MIRROR: "https://rubygems.org"   # در صورت نیاز به آینه لیارا: https://mirror.liara.ir/repository/rubygems
        NPM_MIRROR: "https://mirror.liara.ir/repository/npm/"
    restart: always
    env_file: .env.production
    command: bundle exec puma -C config/puma.rb
    networks:
      - external_network
      - internal_network
    healthcheck:
      test: ['CMD-SHELL', "curl -s --noproxy localhost localhost:3100/health | grep -q 'OK' || exit 1"]
    ports:
      - '127.0.0.1:3100:3100'
    depends_on:
      - db
      - redis
    volumes:
      - ./public/system:/mastodon/public/system

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_REGISTRY: "docker.devneeds.ir"
        DEBIAN_MIRROR: "linux-mirror.liara.ir/repository/debian"
        RUBYGEMS_MIRROR: "https://rubygems.org"
        NPM_MIRROR: "https://mirror.liara.ir/repository/npm/"
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    networks:
      - external_network
      - internal_network
    volumes:
      - ./public/system:/mastodon/public/system
    healthcheck:
      test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 8' || false"]

  streaming:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_REGISTRY: "docker.devneeds.ir"
        DEBIAN_MIRROR: "linux-mirror.liara.ir/repository/debian"
        RUBYGEMS_MIRROR: "https://rubygems.org"
        NPM_MIRROR: "https://mirror.liara.ir/repository/npm/"
    restart: always
    env_file: .env.production
    command: node ./streaming/index.js
    networks:
      - external_network
      - internal_network
    healthcheck:
      test: ['CMD-SHELL', "curl -s --noproxy localhost localhost:4000/api/v1/streaming/health | grep -q 'OK' || exit 1"]
    ports:
      - '127.0.0.1:4000:4000'
    depends_on:
      - db
      - redis

networks:
  external_network:
  internal_network:
    internal: true
